name: Playwright Test Pipeline

# Workflow triggers
on:
  push:
    branches: [ "main" ]       # Run pipeline on push to main
  pull_request:
    branches: [ "main" ]       # Run pipeline on pull request
  workflow_dispatch:           # Allow manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    env :
      BASEURL: ${{ secrets.BASEURL }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      INVALID_USERNAME: ${{ secrets.INVALID_USERNAME }}
      INVALID_PASSWORD: ${{ secrets.INVALID_PASSWORD }}
      

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20     # Change version if required

      - name: Install Dependencies
        run: npm install       # Use npm ci for faster installs if preferred

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: |
          npx playwright test --reporter=html,line

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
